use super::{Category, Severity, VcvdPattern};

pub static PATTERNS: &[VcvdPattern] = &[
    // ── Auth & Identity ──
    VcvdPattern {
        id: "VC-AUTH-001",
        name: "Inconsistent Auth Middleware",
        category: Category::Auth,
        severity: Severity::Critical,
        description: "Authentication middleware is applied to some routes but not others, leaving endpoints unprotected. AI often generates auth for the 'main' routes but forgets admin, webhook, or internal API endpoints.",
        ai_pattern: "AI applies auth on some routes but not others",
        detection_hint: "Compare route definitions against middleware application. Look for routes missing auth wrappers.",
        fix: "Apply auth middleware at the router level, not per-route. Use an allowlist for public endpoints rather than a denylist for protected ones.",
        owasp: "A01:2021 Broken Access Control",
        cwe: 306,
    },
    VcvdPattern {
        id: "VC-AUTH-002",
        name: "Client-Only Validation",
        category: Category::Auth,
        severity: Severity::Critical,
        description: "Role or permission checks exist only in frontend code (React/Vue/Angular). The API accepts any request regardless of the user's actual role. Bypassed by calling the API directly.",
        ai_pattern: "Validation of roles only in the frontend",
        detection_hint: "Check for role checks in frontend components without corresponding server-side middleware.",
        fix: "Every permission check in the frontend MUST have a corresponding server-side check. Frontend checks are UX, not security.",
        owasp: "A01:2021 Broken Access Control",
        cwe: 602,
    },
    VcvdPattern {
        id: "VC-AUTH-003",
        name: "JWT Not Verified",
        category: Category::Auth,
        severity: Severity::Critical,
        description: "JWT tokens are decoded but the signature is never verified. An attacker can forge any token with any claims. Commonly seen as jwt.decode() without verify() or algorithms parameter.",
        ai_pattern: "jwt.decode() without verify()",
        detection_hint: "Search for jwt.decode, jose.decode, jwtDecode without corresponding verify calls.",
        fix: "Always use jwt.verify() with the correct algorithm and secret/public key. Never decode without verification.",
        owasp: "A02:2021 Cryptographic Failures",
        cwe: 347,
    },
    VcvdPattern {
        id: "VC-AUTH-004",
        name: "Hardcoded Service Key",
        category: Category::Auth,
        severity: Severity::Critical,
        description: "Supabase service_role key or equivalent admin credentials are embedded in client-side JavaScript. This key bypasses all RLS policies and gives full database access to anyone who views page source.",
        ai_pattern: "service_role key in client-side code",
        detection_hint: "Search for service_role, SUPABASE_SERVICE_ROLE_KEY, or service key patterns in frontend/client code.",
        fix: "Service keys belong on the server only. Use the anon key client-side with proper RLS policies.",
        owasp: "A07:2021 Identification and Authentication Failures",
        cwe: 798,
    },
    VcvdPattern {
        id: "VC-AUTH-005",
        name: "Missing Token Expiry",
        category: Category::Auth,
        severity: Severity::High,
        description: "JWT tokens are issued without an expiration claim or with an extremely long expiry (30+ days). If a token is stolen, the attacker has indefinite access.",
        ai_pattern: "JWT without exp or with expiry > 30 days",
        detection_hint: "Check JWT creation for expiresIn/exp values. Flag anything over 24 hours without refresh token rotation.",
        fix: "Set token expiry to 15 minutes max. Use refresh token rotation for longer sessions.",
        owasp: "A07:2021 Identification and Authentication Failures",
        cwe: 613,
    },
    VcvdPattern {
        id: "VC-AUTH-006",
        name: "OAuth State Missing",
        category: Category::Auth,
        severity: Severity::High,
        description: "OAuth2 authorization flow lacks the state parameter, enabling CSRF attacks against the login flow. An attacker can force a victim to log into the attacker's account.",
        ai_pattern: "OAuth2 without state parameter",
        detection_hint: "Check OAuth authorization URLs for missing state parameter.",
        fix: "Generate a cryptographically random state value, store it in the session, and verify it on callback.",
        owasp: "A07:2021 Identification and Authentication Failures",
        cwe: 352,
    },
    VcvdPattern {
        id: "VC-AUTH-007",
        name: "Password in Query Param",
        category: Category::Auth,
        severity: Severity::High,
        description: "Passwords or tokens are transmitted via URL query parameters. These appear in server logs, browser history, referrer headers, and proxy logs.",
        ai_pattern: "Password transmitted via GET",
        detection_hint: "Check for password/token/secret in URL query strings or GET request parameters.",
        fix: "Always transmit credentials in the request body over POST with HTTPS.",
        owasp: "A04:2021 Insecure Design",
        cwe: 598,
    },
    VcvdPattern {
        id: "VC-AUTH-008",
        name: "Session Fixation",
        category: Category::Auth,
        severity: Severity::Medium,
        description: "The session ID is not regenerated after successful authentication. An attacker who knows a pre-auth session ID retains access after the victim logs in.",
        ai_pattern: "Session ID not regenerated after login",
        detection_hint: "Check login handlers for session regeneration/rotation calls.",
        fix: "Regenerate the session ID immediately after successful authentication.",
        owasp: "A07:2021 Identification and Authentication Failures",
        cwe: 384,
    },

    // ── Data Access ──
    VcvdPattern {
        id: "VC-DATA-001",
        name: "Universal IDOR",
        category: Category::Data,
        severity: Severity::Critical,
        description: "API endpoints use sequential/guessable IDs without verifying that the requesting user owns the resource. Changing /api/orders/42 to /api/orders/43 returns another user's data.",
        ai_pattern: "Sequential IDs without ownership check",
        detection_hint: "Check API route handlers for resource fetches that don't filter by the authenticated user's ID.",
        fix: "Always include an ownership check: WHERE id = :id AND user_id = :current_user_id. Or use UUIDs and verify ownership separately.",
        owasp: "A01:2021 Broken Access Control",
        cwe: 639,
    },
    VcvdPattern {
        id: "VC-DATA-002",
        name: "Permissive RLS",
        category: Category::Data,
        severity: Severity::Critical,
        description: "Row Level Security policy uses USING (true), effectively disabling access control. Every user can read/write every row. AI often generates this as a 'temporary' solution that ships to production.",
        ai_pattern: "USING (true) on sensitive tables",
        detection_hint: "Search SQL migrations and policies for USING (true) or USING (1=1).",
        fix: "Replace with ownership-based policies: USING (auth.uid() = user_id). Never use USING (true) on tables with user data.",
        owasp: "A01:2021 Broken Access Control",
        cwe: 284,
    },
    VcvdPattern {
        id: "VC-DATA-003",
        name: "Missing RLS",
        category: Category::Data,
        severity: Severity::Critical,
        description: "Supabase/PostgreSQL tables are created without enabling Row Level Security. The anon key grants full read/write access to the entire table via the PostgREST API.",
        ai_pattern: "Table without RLS enabled",
        detection_hint: "Check CREATE TABLE statements for missing ALTER TABLE ... ENABLE ROW LEVEL SECURITY.",
        fix: "Enable RLS on every table: ALTER TABLE tablename ENABLE ROW LEVEL SECURITY; Then create appropriate policies.",
        owasp: "A01:2021 Broken Access Control",
        cwe: 862,
    },
    VcvdPattern {
        id: "VC-DATA-004",
        name: "SELECT * Exposure",
        category: Category::Data,
        severity: Severity::High,
        description: "SELECT * queries return all columns including password hashes, internal IDs, PII, and audit fields that shouldn't be exposed to the client.",
        ai_pattern: "SELECT * that includes password hash and PII",
        detection_hint: "Search for SELECT * on tables that contain sensitive columns.",
        fix: "Explicitly list columns in SELECT. Create database views that exclude sensitive fields for client-facing queries.",
        owasp: "A01:2021 Broken Access Control",
        cwe: 200,
    },
    VcvdPattern {
        id: "VC-DATA-005",
        name: "Mass Assignment",
        category: Category::Data,
        severity: Severity::High,
        description: "Request body is spread directly into a database insert/update without whitelisting fields. An attacker can set is_admin: true, role: 'admin', or any other field.",
        ai_pattern: "Spread operator without field whitelist",
        detection_hint: "Search for ...req.body, ...body, Object.assign(model, req.body) or similar patterns.",
        fix: "Destructure only the fields you expect: const { name, email } = req.body; Never spread the entire body.",
        owasp: "A04:2021 Insecure Design",
        cwe: 915,
    },
    VcvdPattern {
        id: "VC-DATA-006",
        name: "GraphQL Introspection",
        category: Category::Data,
        severity: Severity::Medium,
        description: "GraphQL introspection is enabled in production, exposing the entire schema including internal types, mutations, and field names. Attackers use this to map the attack surface.",
        ai_pattern: "Schema exposed in production",
        detection_hint: "Send an introspection query to the GraphQL endpoint and check if it returns the schema.",
        fix: "Disable introspection in production. Most GraphQL servers have an introspection: false option.",
        owasp: "A05:2021 Security Misconfiguration",
        cwe: 200,
    },
    VcvdPattern {
        id: "VC-DATA-007",
        name: "N+1 as DoS",
        category: Category::Data,
        severity: Severity::Medium,
        description: "Unbounded N+1 queries allow an attacker to trigger thousands of database queries with a single API call by requesting a large list with nested relations.",
        ai_pattern: "N+1 queries without limits",
        detection_hint: "Check for endpoints that load relations in a loop without pagination or depth limits.",
        fix: "Add pagination (limit/offset), depth limits for nested queries, and query complexity analysis for GraphQL.",
        owasp: "A04:2021 Insecure Design",
        cwe: 400,
    },
    VcvdPattern {
        id: "VC-DATA-008",
        name: "Tenant Isolation Missing",
        category: Category::Data,
        severity: Severity::Critical,
        description: "Multi-tenant application doesn't filter by tenant_id in queries. Users from Tenant A can see data from Tenant B.",
        ai_pattern: "Multi-tenant without tenant_id filter",
        detection_hint: "Check database queries for missing tenant_id/org_id WHERE clauses in multi-tenant apps.",
        fix: "Apply tenant filtering at the database level (RLS with tenant_id) or via mandatory middleware that injects the tenant filter.",
        owasp: "A01:2021 Broken Access Control",
        cwe: 668,
    },

    // ── Injection ──
    VcvdPattern {
        id: "VC-INJ-001",
        name: "String Concatenation SQL",
        category: Category::Injection,
        severity: Severity::Critical,
        description: "SQL queries built with string concatenation or template literals. Allows full SQL injection: data theft, modification, or deletion.",
        ai_pattern: "Template literals in SQL queries",
        detection_hint: "Search for string interpolation inside SQL queries: f-strings, template literals, string concat with +.",
        fix: "Use parameterized queries / prepared statements. Every database driver supports them.",
        owasp: "A03:2021 Injection",
        cwe: 89,
    },
    VcvdPattern {
        id: "VC-INJ-002",
        name: "Reflected XSS",
        category: Category::Injection,
        severity: Severity::High,
        description: "User input from URL parameters or form fields is rendered in HTML without sanitization. Attacker crafts a URL that executes JavaScript in the victim's browser.",
        ai_pattern: "User input in HTML without sanitization",
        detection_hint: "Search for innerHTML, document.write, or server-side template rendering with unescaped user input.",
        fix: "Use framework auto-escaping (React JSX, Vue templates). If you must set HTML, sanitize with DOMPurify or equivalent.",
        owasp: "A03:2021 Injection",
        cwe: 79,
    },
    VcvdPattern {
        id: "VC-INJ-003",
        name: "Stored XSS",
        category: Category::Injection,
        severity: Severity::Critical,
        description: "User-submitted content is saved to the database and rendered to other users without sanitization. Affects every user who views the content.",
        ai_pattern: "User input saved and rendered unsanitized",
        detection_hint: "Trace user input from form submission through storage to rendering. Check for missing sanitization at any stage.",
        fix: "Sanitize on output, not just on input. Use DOMPurify for HTML, or store as plain text and render with auto-escaping.",
        owasp: "A03:2021 Injection",
        cwe: 79,
    },
    VcvdPattern {
        id: "VC-INJ-004",
        name: "Command Injection",
        category: Category::Injection,
        severity: Severity::Critical,
        description: "User input passed to shell commands via exec(), spawn(), system(), or os.popen(). Attacker appends ; rm -rf / or pipes to exfiltrate data.",
        ai_pattern: "Input in exec() / spawn()",
        detection_hint: "Search for exec, spawn, system, popen with string concatenation or interpolation involving user input.",
        fix: "Avoid shell execution entirely. If unavoidable, use array-based APIs (spawn with args array) and validate input against a strict allowlist.",
        owasp: "A03:2021 Injection",
        cwe: 78,
    },
    VcvdPattern {
        id: "VC-INJ-005",
        name: "Path Traversal",
        category: Category::Injection,
        severity: Severity::High,
        description: "User input used in file paths without validation. Attacker uses ../../etc/passwd to read arbitrary files or overwrite critical files.",
        ai_pattern: "File path not validated",
        detection_hint: "Search for file operations (readFile, open, path.join) that include user-controlled input.",
        fix: "Resolve the path and verify it stays within the intended directory. Use path.resolve() and check startsWith(baseDir).",
        owasp: "A01:2021 Broken Access Control",
        cwe: 22,
    },
    VcvdPattern {
        id: "VC-INJ-006",
        name: "SSRF",
        category: Category::Injection,
        severity: Severity::High,
        description: "Server-side code fetches a URL provided by the user without validation. Attacker points it to internal services (metadata endpoint, localhost admin panel, internal APIs).",
        ai_pattern: "User-provided URL used in server-side fetch",
        detection_hint: "Search for fetch/axios/requests calls where the URL comes from user input.",
        fix: "Validate and allowlist destination hosts. Block private IP ranges (10.x, 172.16-31.x, 192.168.x, 169.254.x, localhost). Use a URL parser, don't regex.",
        owasp: "A10:2021 Server-Side Request Forgery",
        cwe: 918,
    },
    VcvdPattern {
        id: "VC-INJ-007",
        name: "Template Injection",
        category: Category::Injection,
        severity: Severity::High,
        description: "User input embedded in server-side template strings (Jinja2, EJS, Handlebars). Can lead to remote code execution.",
        ai_pattern: "Input in server-side template string",
        detection_hint: "Search for user input passed directly into template.render() or similar template engine calls.",
        fix: "Never pass user input as template source. Pass it as template data/context instead.",
        owasp: "A03:2021 Injection",
        cwe: 94,
    },
    VcvdPattern {
        id: "VC-INJ-008",
        name: "NoSQL Injection",
        category: Category::Injection,
        severity: Severity::High,
        description: "MongoDB/NoSQL operators in user-controlled JSON input. Attacker sends {\"$gt\": \"\"} as password to bypass authentication.",
        ai_pattern: "MongoDB operators in JSON input",
        detection_hint: "Search for query construction using unsanitized request body fields in MongoDB/Mongoose queries.",
        fix: "Validate input types strictly. Reject objects where strings are expected. Use mongo-sanitize or equivalent.",
        owasp: "A03:2021 Injection",
        cwe: 943,
    },

    // ── Infrastructure ──
    VcvdPattern {
        id: "VC-INFRA-001",
        name: "Debug Mode in Prod",
        category: Category::Infra,
        severity: Severity::High,
        description: "Debug mode or development settings enabled in production. Exposes stack traces, internal paths, environment variables, and sometimes interactive debuggers.",
        ai_pattern: "DEBUG=true, stack traces exposed",
        detection_hint: "Check for DEBUG=true, NODE_ENV=development, FLASK_DEBUG=1, or detailed error pages in production responses.",
        fix: "Set DEBUG=false and NODE_ENV=production. Use a generic error page in production. Log details server-side only.",
        owasp: "A05:2021 Security Misconfiguration",
        cwe: 215,
    },
    VcvdPattern {
        id: "VC-INFRA-002",
        name: "Permissive CORS",
        category: Category::Infra,
        severity: Severity::High,
        description: "Access-Control-Allow-Origin set to * combined with Access-Control-Allow-Credentials. Any website can make authenticated requests to your API.",
        ai_pattern: "Access-Control-Allow-Origin: * with credentials",
        detection_hint: "Check response headers for overly permissive CORS configuration.",
        fix: "Set specific allowed origins. Never use * with credentials. Validate the Origin header against an allowlist.",
        owasp: "A05:2021 Security Misconfiguration",
        cwe: 942,
    },
    VcvdPattern {
        id: "VC-INFRA-003",
        name: "Missing Security Headers",
        category: Category::Infra,
        severity: Severity::Medium,
        description: "Response is missing security headers: Strict-Transport-Security, X-Content-Type-Options, X-Frame-Options, Content-Security-Policy.",
        ai_pattern: "No HSTS, X-Content-Type-Options, X-Frame",
        detection_hint: "Check HTTP response headers for missing security headers.",
        fix: "Add Strict-Transport-Security, X-Content-Type-Options: nosniff, X-Frame-Options: DENY, and a Content-Security-Policy.",
        owasp: "A05:2021 Security Misconfiguration",
        cwe: 693,
    },
    VcvdPattern {
        id: "VC-INFRA-004",
        name: "Open Docker Ports",
        category: Category::Infra,
        severity: Severity::Medium,
        description: "Docker containers expose unnecessary ports to the host or public network. Database ports, debug ports, or internal service ports are accessible externally.",
        ai_pattern: "Unnecessary ports exposed",
        detection_hint: "Check docker-compose.yml and Dockerfile for ports that shouldn't be public.",
        fix: "Only expose ports that need to be public. Use Docker networks for inter-container communication.",
        owasp: "A05:2021 Security Misconfiguration",
        cwe: 284,
    },
    VcvdPattern {
        id: "VC-INFRA-005",
        name: "Unencrypted Storage",
        category: Category::Infra,
        severity: Severity::Medium,
        description: "User-uploaded files stored without encryption. If the storage is compromised, all files are readable.",
        ai_pattern: "File upload without encryption",
        detection_hint: "Check file storage configuration for encryption-at-rest settings.",
        fix: "Enable server-side encryption on the storage bucket (S3 SSE, GCS CMEK). Encrypt sensitive files before upload.",
        owasp: "A02:2021 Cryptographic Failures",
        cwe: 311,
    },
    VcvdPattern {
        id: "VC-INFRA-006",
        name: "Weak TLS",
        category: Category::Infra,
        severity: Severity::Medium,
        description: "Server accepts TLS 1.0 or 1.1 connections, which have known vulnerabilities (BEAST, POODLE).",
        ai_pattern: "TLS 1.0/1.1 enabled",
        detection_hint: "Probe the server for supported TLS versions.",
        fix: "Disable TLS 1.0 and 1.1. Require TLS 1.2+ with strong cipher suites. Prefer TLS 1.3.",
        owasp: "A02:2021 Cryptographic Failures",
        cwe: 326,
    },
    VcvdPattern {
        id: "VC-INFRA-007",
        name: "Exposed Admin Panel",
        category: Category::Infra,
        severity: Severity::High,
        description: "Admin panel accessible from the public internet without IP restriction. Combined with weak credentials, this leads to full system compromise.",
        ai_pattern: "Admin without IP restriction",
        detection_hint: "Check if /admin, /dashboard, or admin subdomains are reachable from the public internet.",
        fix: "Restrict admin panel access by IP allowlist or VPN. Add MFA for admin accounts.",
        owasp: "A01:2021 Broken Access Control",
        cwe: 284,
    },
    VcvdPattern {
        id: "VC-INFRA-008",
        name: "Default Credentials",
        category: Category::Infra,
        severity: Severity::Critical,
        description: "Default usernames/passwords left unchanged on databases, admin panels, or services. Attackers try these first.",
        ai_pattern: "Default credentials not changed",
        detection_hint: "Check for common default credentials (admin/admin, root/root, postgres/postgres).",
        fix: "Change all default credentials during initial setup. Use strong, unique passwords. Automate credential rotation.",
        owasp: "A07:2021 Identification and Authentication Failures",
        cwe: 1392,
    },

    // ── Frontend ──
    VcvdPattern {
        id: "VC-FE-001",
        name: "Secrets in Bundle",
        category: Category::Frontend,
        severity: Severity::Critical,
        description: "API keys, service keys, or secrets embedded in the JavaScript bundle. Visible to anyone who opens browser DevTools.",
        ai_pattern: "API key in JavaScript bundle",
        detection_hint: "Search JS bundles for patterns: sk_live_, sk-, AKIA, ghp_, glpat-, private_key, service_role.",
        fix: "Move secrets to server-side environment variables. Use a backend proxy for API calls that need secret keys.",
        owasp: "A07:2021 Identification and Authentication Failures",
        cwe: 798,
    },
    VcvdPattern {
        id: "VC-FE-002",
        name: "Client-Side Auth Guard",
        category: Category::Frontend,
        severity: Severity::High,
        description: "Route protection implemented only via frontend router guards (React Router, Vue Router). The API serves data regardless of auth state.",
        ai_pattern: "Route protection only via Router",
        detection_hint: "Check if protected routes have corresponding server-side auth checks on the data-fetching endpoints.",
        fix: "Frontend route guards are UX conveniences. The API MUST verify auth independently on every request.",
        owasp: "A01:2021 Broken Access Control",
        cwe: 602,
    },
    VcvdPattern {
        id: "VC-FE-003",
        name: "LocalStorage Tokens",
        category: Category::Frontend,
        severity: Severity::Medium,
        description: "JWT or session tokens stored in localStorage. Any XSS vulnerability gives the attacker persistent access to the user's account.",
        ai_pattern: "JWT in localStorage",
        detection_hint: "Search for localStorage.setItem with token/jwt/session values.",
        fix: "Store tokens in httpOnly cookies with Secure and SameSite flags. These are inaccessible to JavaScript.",
        owasp: "A07:2021 Identification and Authentication Failures",
        cwe: 922,
    },
    VcvdPattern {
        id: "VC-FE-004",
        name: "Missing CSRF",
        category: Category::Frontend,
        severity: Severity::High,
        description: "State-changing forms and API endpoints don't implement CSRF protection. An attacker's website can submit forms on behalf of logged-in users.",
        ai_pattern: "Form without CSRF token",
        detection_hint: "Check forms and state-changing endpoints for CSRF tokens or SameSite cookie usage.",
        fix: "Use SameSite=Strict cookies (eliminates most CSRF) or implement CSRF tokens for forms.",
        owasp: "A01:2021 Broken Access Control",
        cwe: 352,
    },
    VcvdPattern {
        id: "VC-FE-005",
        name: "Unvalidated Redirects",
        category: Category::Frontend,
        severity: Severity::Medium,
        description: "Redirect URL taken from query parameters without validation. Attacker crafts a link that redirects to a phishing page after login.",
        ai_pattern: "Redirect URL from query param",
        detection_hint: "Search for redirect logic that reads from req.query.redirect or similar without validation.",
        fix: "Validate redirect URLs against an allowlist of domains. Only allow relative paths or known hosts.",
        owasp: "A01:2021 Broken Access Control",
        cwe: 601,
    },
    VcvdPattern {
        id: "VC-FE-006",
        name: "Insecure PostMessage",
        category: Category::Frontend,
        severity: Severity::Medium,
        description: "window.postMessage used without checking the origin of incoming messages. Any iframe or window can send messages to your application.",
        ai_pattern: "postMessage without origin check",
        detection_hint: "Search for addEventListener('message') handlers that don't verify event.origin.",
        fix: "Always check event.origin against expected values in message event handlers.",
        owasp: "A04:2021 Insecure Design",
        cwe: 346,
    },
    VcvdPattern {
        id: "VC-FE-007",
        name: "Source Maps in Prod",
        category: Category::Frontend,
        severity: Severity::Low,
        description: "JavaScript source map files (.map) are accessible in production. Reveals the original source code, making it easier to find vulnerabilities.",
        ai_pattern: ".map files accessible",
        detection_hint: "Check if .js.map files are served by the production server.",
        fix: "Remove source maps from production builds or restrict access to them.",
        owasp: "A05:2021 Security Misconfiguration",
        cwe: 540,
    },
    VcvdPattern {
        id: "VC-FE-008",
        name: "Form Autofill Leak",
        category: Category::Frontend,
        severity: Severity::Low,
        description: "Sensitive form fields (credit card, SSN) don't disable browser autofill. On shared computers, previous user's data may auto-populate.",
        ai_pattern: "Sensitive fields without autocomplete='off'",
        detection_hint: "Check sensitive input fields for autocomplete attribute.",
        fix: "Add autocomplete='off' or autocomplete='new-password' to sensitive form fields.",
        owasp: "A04:2021 Insecure Design",
        cwe: 200,
    },

    // -- Business Logic --
    VcvdPattern {
        id: "VC-BIZ-001",
        name: "Race Condition in Transaction",
        category: Category::Data,
        severity: Severity::High,
        description: "Non-atomic read-then-write operations allow race conditions. Two concurrent requests can both read the same balance, both deduct, resulting in negative balance.",
        ai_pattern: "AI generates sequential code without considering concurrency",
        detection_hint: "Look for read-then-write patterns on shared resources without database transactions or locking.",
        fix: "Use database transactions with appropriate isolation level. Use SELECT FOR UPDATE or optimistic locking.",
        owasp: "A04:2021 Insecure Design",
        cwe: 362,
    },
    VcvdPattern {
        id: "VC-BIZ-002",
        name: "Missing Rate Limit on Sensitive Action",
        category: Category::Auth,
        severity: Severity::High,
        description: "Password reset, email verification, or SMS endpoints have no rate limiting, enabling brute force or resource exhaustion.",
        ai_pattern: "AI generates the endpoint without rate limiting",
        detection_hint: "Check password reset, email verification, and SMS endpoints for rate limiting middleware.",
        fix: "Add per-IP and per-account rate limiting on sensitive endpoints.",
        owasp: "A07:2021 Identification and Authentication Failures",
        cwe: 307,
    },
    VcvdPattern {
        id: "VC-BIZ-003",
        name: "Enumeration via Timing",
        category: Category::Auth,
        severity: Severity::Medium,
        description: "Login endpoint responds faster for non-existent users than existing ones, allowing username enumeration.",
        ai_pattern: "AI returns early for \"user not found\" without constant-time comparison",
        detection_hint: "Measure response times for valid vs invalid usernames on login endpoints.",
        fix: "Always perform the full auth flow including password hash comparison, even for non-existent users.",
        owasp: "A07:2021 Identification and Authentication Failures",
        cwe: 208,
    },
    VcvdPattern {
        id: "VC-BIZ-004",
        name: "Price Manipulation",
        category: Category::Data,
        severity: Severity::Critical,
        description: "Client-submitted price is used directly in the order without server-side validation against the actual product price.",
        ai_pattern: "AI trusts the price from the frontend form",
        detection_hint: "Check order/checkout endpoints for client-submitted price fields used without server-side lookup.",
        fix: "Always look up the price server-side. Never trust client-submitted monetary values.",
        owasp: "A04:2021 Insecure Design",
        cwe: 472,
    },

    // -- API Specific --
    VcvdPattern {
        id: "VC-API-001",
        name: "Excessive Data Exposure",
        category: Category::Data,
        severity: Severity::High,
        description: "API returns full objects including internal fields, timestamps, foreign keys, and related data that the client doesn't need.",
        ai_pattern: "AI returns the full database model to the client",
        detection_hint: "Check API responses for internal fields like password hashes, internal IDs, or audit timestamps.",
        fix: "Use response DTOs/serializers that explicitly include only the fields the client needs.",
        owasp: "A01:2021 Broken Access Control",
        cwe: 200,
    },
    VcvdPattern {
        id: "VC-API-002",
        name: "Missing Pagination",
        category: Category::Data,
        severity: Severity::Medium,
        description: "List endpoints return all records without pagination. An attacker can dump the entire table or cause OOM.",
        ai_pattern: "AI generates findAll() without limit/offset",
        detection_hint: "Check list endpoints for missing limit/offset or page/pageSize parameters.",
        fix: "Add mandatory pagination with a maximum page size. Default to 20, cap at 100.",
        owasp: "A04:2021 Insecure Design",
        cwe: 400,
    },
    VcvdPattern {
        id: "VC-API-003",
        name: "Broken Function Level Auth",
        category: Category::Auth,
        severity: Severity::Critical,
        description: "Admin endpoints exist at predictable paths (e.g., /api/admin/users) without role verification. Any authenticated user can call admin functions.",
        ai_pattern: "AI creates admin routes without role-checking middleware",
        detection_hint: "Check admin route definitions for missing role-based access control middleware.",
        fix: "Apply role-based middleware at the router level for admin routes.",
        owasp: "A01:2021 Broken Access Control",
        cwe: 285,
    },
];
